//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace babgvant.Emby.MythTv.MythTvGuide {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Program", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class Program : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CatTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RepeatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VideoPropsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AudioPropsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubPropsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgramFlagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AirdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InetrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EpisodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvGuide.ChannelInfo ChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvGuide.RecordingInfo RecordingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvGuide.ArtworkInfoList ArtworkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SubTitle {
            get {
                return this.SubTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTitleField, value) != true)) {
                    this.SubTitleField = value;
                    this.RaisePropertyChanged("SubTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CatType {
            get {
                return this.CatTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CatTypeField, value) != true)) {
                    this.CatTypeField = value;
                    this.RaisePropertyChanged("CatType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool Repeat {
            get {
                return this.RepeatField;
            }
            set {
                if ((this.RepeatField.Equals(value) != true)) {
                    this.RepeatField = value;
                    this.RaisePropertyChanged("Repeat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int VideoProps {
            get {
                return this.VideoPropsField;
            }
            set {
                if ((this.VideoPropsField.Equals(value) != true)) {
                    this.VideoPropsField = value;
                    this.RaisePropertyChanged("VideoProps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int AudioProps {
            get {
                return this.AudioPropsField;
            }
            set {
                if ((this.AudioPropsField.Equals(value) != true)) {
                    this.AudioPropsField = value;
                    this.RaisePropertyChanged("AudioProps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int SubProps {
            get {
                return this.SubPropsField;
            }
            set {
                if ((this.SubPropsField.Equals(value) != true)) {
                    this.SubPropsField = value;
                    this.RaisePropertyChanged("SubProps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SeriesId {
            get {
                return this.SeriesIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesIdField, value) != true)) {
                    this.SeriesIdField = value;
                    this.RaisePropertyChanged("SeriesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ProgramId {
            get {
                return this.ProgramIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramIdField, value) != true)) {
                    this.ProgramIdField = value;
                    this.RaisePropertyChanged("ProgramId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public double Stars {
            get {
                return this.StarsField;
            }
            set {
                if ((this.StarsField.Equals(value) != true)) {
                    this.StarsField = value;
                    this.RaisePropertyChanged("Stars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public long FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.Nullable<System.DateTime> LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int ProgramFlags {
            get {
                return this.ProgramFlagsField;
            }
            set {
                if ((this.ProgramFlagsField.Equals(value) != true)) {
                    this.ProgramFlagsField = value;
                    this.RaisePropertyChanged("ProgramFlags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string HostName {
            get {
                return this.HostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostNameField, value) != true)) {
                    this.HostNameField = value;
                    this.RaisePropertyChanged("HostName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string Airdate {
            get {
                return this.AirdateField;
            }
            set {
                if ((object.ReferenceEquals(this.AirdateField, value) != true)) {
                    this.AirdateField = value;
                    this.RaisePropertyChanged("Airdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Inetref {
            get {
                return this.InetrefField;
            }
            set {
                if ((object.ReferenceEquals(this.InetrefField, value) != true)) {
                    this.InetrefField = value;
                    this.RaisePropertyChanged("Inetref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public int Season {
            get {
                return this.SeasonField;
            }
            set {
                if ((this.SeasonField.Equals(value) != true)) {
                    this.SeasonField = value;
                    this.RaisePropertyChanged("Season");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public int Episode {
            get {
                return this.EpisodeField;
            }
            set {
                if ((this.EpisodeField.Equals(value) != true)) {
                    this.EpisodeField = value;
                    this.RaisePropertyChanged("Episode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public babgvant.Emby.MythTv.MythTvGuide.ChannelInfo Channel {
            get {
                return this.ChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelField, value) != true)) {
                    this.ChannelField = value;
                    this.RaisePropertyChanged("Channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public babgvant.Emby.MythTv.MythTvGuide.RecordingInfo Recording {
            get {
                return this.RecordingField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordingField, value) != true)) {
                    this.RecordingField = value;
                    this.RaisePropertyChanged("Recording");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public babgvant.Emby.MythTv.MythTvGuide.ArtworkInfoList Artwork {
            get {
                return this.ArtworkField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtworkField, value) != true)) {
                    this.ArtworkField = value;
                    this.RaisePropertyChanged("Artwork");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelInfo", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class ChannelInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ChanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChanNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallSignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint MplexIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint TransportIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ServiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint NetworkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ATSCMajorChanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ATSCMinorChanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModulationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FrequencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FrequencyTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FineTuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIStandardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChanFiltersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InputIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommFreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseEITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLTVIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultAuthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvGuide.Program[] ProgramsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ChanId {
            get {
                return this.ChanIdField;
            }
            set {
                if ((this.ChanIdField.Equals(value) != true)) {
                    this.ChanIdField = value;
                    this.RaisePropertyChanged("ChanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ChanNum {
            get {
                return this.ChanNumField;
            }
            set {
                if ((object.ReferenceEquals(this.ChanNumField, value) != true)) {
                    this.ChanNumField = value;
                    this.RaisePropertyChanged("ChanNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CallSign {
            get {
                return this.CallSignField;
            }
            set {
                if ((object.ReferenceEquals(this.CallSignField, value) != true)) {
                    this.CallSignField = value;
                    this.RaisePropertyChanged("CallSign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IconURL {
            get {
                return this.IconURLField;
            }
            set {
                if ((object.ReferenceEquals(this.IconURLField, value) != true)) {
                    this.IconURLField = value;
                    this.RaisePropertyChanged("IconURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ChannelName {
            get {
                return this.ChannelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelNameField, value) != true)) {
                    this.ChannelNameField = value;
                    this.RaisePropertyChanged("ChannelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public uint MplexId {
            get {
                return this.MplexIdField;
            }
            set {
                if ((this.MplexIdField.Equals(value) != true)) {
                    this.MplexIdField = value;
                    this.RaisePropertyChanged("MplexId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public uint TransportId {
            get {
                return this.TransportIdField;
            }
            set {
                if ((this.TransportIdField.Equals(value) != true)) {
                    this.TransportIdField = value;
                    this.RaisePropertyChanged("TransportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public uint ServiceId {
            get {
                return this.ServiceIdField;
            }
            set {
                if ((this.ServiceIdField.Equals(value) != true)) {
                    this.ServiceIdField = value;
                    this.RaisePropertyChanged("ServiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public uint NetworkId {
            get {
                return this.NetworkIdField;
            }
            set {
                if ((this.NetworkIdField.Equals(value) != true)) {
                    this.NetworkIdField = value;
                    this.RaisePropertyChanged("NetworkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public uint ATSCMajorChan {
            get {
                return this.ATSCMajorChanField;
            }
            set {
                if ((this.ATSCMajorChanField.Equals(value) != true)) {
                    this.ATSCMajorChanField = value;
                    this.RaisePropertyChanged("ATSCMajorChan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public uint ATSCMinorChan {
            get {
                return this.ATSCMinorChanField;
            }
            set {
                if ((this.ATSCMinorChanField.Equals(value) != true)) {
                    this.ATSCMinorChanField = value;
                    this.RaisePropertyChanged("ATSCMinorChan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Format {
            get {
                return this.FormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatField, value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Modulation {
            get {
                return this.ModulationField;
            }
            set {
                if ((object.ReferenceEquals(this.ModulationField, value) != true)) {
                    this.ModulationField = value;
                    this.RaisePropertyChanged("Modulation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public long Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string FrequencyId {
            get {
                return this.FrequencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FrequencyIdField, value) != true)) {
                    this.FrequencyIdField = value;
                    this.RaisePropertyChanged("FrequencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string FrequencyTable {
            get {
                return this.FrequencyTableField;
            }
            set {
                if ((object.ReferenceEquals(this.FrequencyTableField, value) != true)) {
                    this.FrequencyTableField = value;
                    this.RaisePropertyChanged("FrequencyTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int FineTune {
            get {
                return this.FineTuneField;
            }
            set {
                if ((this.FineTuneField.Equals(value) != true)) {
                    this.FineTuneField = value;
                    this.RaisePropertyChanged("FineTune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string SIStandard {
            get {
                return this.SIStandardField;
            }
            set {
                if ((object.ReferenceEquals(this.SIStandardField, value) != true)) {
                    this.SIStandardField = value;
                    this.RaisePropertyChanged("SIStandard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string ChanFilters {
            get {
                return this.ChanFiltersField;
            }
            set {
                if ((object.ReferenceEquals(this.ChanFiltersField, value) != true)) {
                    this.ChanFiltersField = value;
                    this.RaisePropertyChanged("ChanFilters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public int SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((this.SourceIdField.Equals(value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public int InputId {
            get {
                return this.InputIdField;
            }
            set {
                if ((this.InputIdField.Equals(value) != true)) {
                    this.InputIdField = value;
                    this.RaisePropertyChanged("InputId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public int CommFree {
            get {
                return this.CommFreeField;
            }
            set {
                if ((this.CommFreeField.Equals(value) != true)) {
                    this.CommFreeField = value;
                    this.RaisePropertyChanged("CommFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public bool UseEIT {
            get {
                return this.UseEITField;
            }
            set {
                if ((this.UseEITField.Equals(value) != true)) {
                    this.UseEITField = value;
                    this.RaisePropertyChanged("UseEIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public bool Visible {
            get {
                return this.VisibleField;
            }
            set {
                if ((this.VisibleField.Equals(value) != true)) {
                    this.VisibleField = value;
                    this.RaisePropertyChanged("Visible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string XMLTVID {
            get {
                return this.XMLTVIDField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLTVIDField, value) != true)) {
                    this.XMLTVIDField = value;
                    this.RaisePropertyChanged("XMLTVID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string DefaultAuth {
            get {
                return this.DefaultAuthField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultAuthField, value) != true)) {
                    this.DefaultAuthField = value;
                    this.RaisePropertyChanged("DefaultAuth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public babgvant.Emby.MythTv.MythTvGuide.Program[] Programs {
            get {
                return this.ProgramsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramsField, value) != true)) {
                    this.ProgramsField = value;
                    this.RaisePropertyChanged("Programs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordingInfo", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class RecordingInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartTsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndTsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorageGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DupInTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DupMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EncoderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> StartTs {
            get {
                return this.StartTsField;
            }
            set {
                if ((this.StartTsField.Equals(value) != true)) {
                    this.StartTsField = value;
                    this.RaisePropertyChanged("StartTs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> EndTs {
            get {
                return this.EndTsField;
            }
            set {
                if ((this.EndTsField.Equals(value) != true)) {
                    this.EndTsField = value;
                    this.RaisePropertyChanged("EndTs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((this.RecordIdField.Equals(value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RecGroup {
            get {
                return this.RecGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.RecGroupField, value) != true)) {
                    this.RecGroupField = value;
                    this.RaisePropertyChanged("RecGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PlayGroup {
            get {
                return this.PlayGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayGroupField, value) != true)) {
                    this.PlayGroupField = value;
                    this.RaisePropertyChanged("PlayGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string StorageGroup {
            get {
                return this.StorageGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageGroupField, value) != true)) {
                    this.StorageGroupField = value;
                    this.RaisePropertyChanged("StorageGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int RecType {
            get {
                return this.RecTypeField;
            }
            set {
                if ((this.RecTypeField.Equals(value) != true)) {
                    this.RecTypeField = value;
                    this.RaisePropertyChanged("RecType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int DupInType {
            get {
                return this.DupInTypeField;
            }
            set {
                if ((this.DupInTypeField.Equals(value) != true)) {
                    this.DupInTypeField = value;
                    this.RaisePropertyChanged("DupInType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int DupMethod {
            get {
                return this.DupMethodField;
            }
            set {
                if ((this.DupMethodField.Equals(value) != true)) {
                    this.DupMethodField = value;
                    this.RaisePropertyChanged("DupMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int EncoderId {
            get {
                return this.EncoderIdField;
            }
            set {
                if ((this.EncoderIdField.Equals(value) != true)) {
                    this.EncoderIdField = value;
                    this.RaisePropertyChanged("EncoderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtworkInfoList", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class ArtworkInfoList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvGuide.ArtworkInfo[] ArtworkInfosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public babgvant.Emby.MythTv.MythTvGuide.ArtworkInfo[] ArtworkInfos {
            get {
                return this.ArtworkInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtworkInfosField, value) != true)) {
                    this.ArtworkInfosField = value;
                    this.RaisePropertyChanged("ArtworkInfos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtworkInfo", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class ArtworkInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorageGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StorageGroup {
            get {
                return this.StorageGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageGroupField, value) != true)) {
                    this.StorageGroupField = value;
                    this.RaisePropertyChanged("StorageGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramGuide", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class ProgramGuide : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartChanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndChanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfChannelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AsOfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProtoVerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvGuide.ChannelInfo[] ChannelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int StartChanId {
            get {
                return this.StartChanIdField;
            }
            set {
                if ((this.StartChanIdField.Equals(value) != true)) {
                    this.StartChanIdField = value;
                    this.RaisePropertyChanged("StartChanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int EndChanId {
            get {
                return this.EndChanIdField;
            }
            set {
                if ((this.EndChanIdField.Equals(value) != true)) {
                    this.EndChanIdField = value;
                    this.RaisePropertyChanged("EndChanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int NumOfChannels {
            get {
                return this.NumOfChannelsField;
            }
            set {
                if ((this.NumOfChannelsField.Equals(value) != true)) {
                    this.NumOfChannelsField = value;
                    this.RaisePropertyChanged("NumOfChannels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((this.DetailsField.Equals(value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> AsOf {
            get {
                return this.AsOfField;
            }
            set {
                if ((this.AsOfField.Equals(value) != true)) {
                    this.AsOfField = value;
                    this.RaisePropertyChanged("AsOf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ProtoVer {
            get {
                return this.ProtoVerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProtoVerField, value) != true)) {
                    this.ProtoVerField = value;
                    this.RaisePropertyChanged("ProtoVer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public babgvant.Emby.MythTv.MythTvGuide.ChannelInfo[] Channels {
            get {
                return this.ChannelsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelsField, value) != true)) {
                    this.ChannelsField = value;
                    this.RaisePropertyChanged("Channels");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mythtv.org", ConfigurationName="MythTvGuide.Guide")]
    public interface Guide {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Guide/GetChannelIcon", ReplyAction="http://mythtv.org/Guide/GetChannelIconResponse")]
        string GetChannelIcon(System.Nullable<int> ChanId, System.Nullable<int> Width, System.Nullable<int> Height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Guide/GetChannelIcon", ReplyAction="http://mythtv.org/Guide/GetChannelIconResponse")]
        System.Threading.Tasks.Task<string> GetChannelIconAsync(System.Nullable<int> ChanId, System.Nullable<int> Width, System.Nullable<int> Height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Guide/GetProgramDetails", ReplyAction="http://mythtv.org/Guide/GetProgramDetailsResponse")]
        babgvant.Emby.MythTv.MythTvGuide.Program GetProgramDetails(System.Nullable<int> ChanId, System.Nullable<System.DateTime> StartTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Guide/GetProgramDetails", ReplyAction="http://mythtv.org/Guide/GetProgramDetailsResponse")]
        System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvGuide.Program> GetProgramDetailsAsync(System.Nullable<int> ChanId, System.Nullable<System.DateTime> StartTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Guide/GetProgramGuide", ReplyAction="http://mythtv.org/Guide/GetProgramGuideResponse")]
        babgvant.Emby.MythTv.MythTvGuide.ProgramGuide GetProgramGuide(System.Nullable<System.DateTime> StartTime, System.Nullable<System.DateTime> EndTime, System.Nullable<int> StartChanId, System.Nullable<int> NumChannels, System.Nullable<bool> Details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Guide/GetProgramGuide", ReplyAction="http://mythtv.org/Guide/GetProgramGuideResponse")]
        System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvGuide.ProgramGuide> GetProgramGuideAsync(System.Nullable<System.DateTime> StartTime, System.Nullable<System.DateTime> EndTime, System.Nullable<int> StartChanId, System.Nullable<int> NumChannels, System.Nullable<bool> Details);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GuideChannel : babgvant.Emby.MythTv.MythTvGuide.Guide, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuideClient : System.ServiceModel.ClientBase<babgvant.Emby.MythTv.MythTvGuide.Guide>, babgvant.Emby.MythTv.MythTvGuide.Guide {
        
        public GuideClient() {
        }
        
        public GuideClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuideClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuideClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuideClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetChannelIcon(System.Nullable<int> ChanId, System.Nullable<int> Width, System.Nullable<int> Height) {
            return base.Channel.GetChannelIcon(ChanId, Width, Height);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelIconAsync(System.Nullable<int> ChanId, System.Nullable<int> Width, System.Nullable<int> Height) {
            return base.Channel.GetChannelIconAsync(ChanId, Width, Height);
        }
        
        public babgvant.Emby.MythTv.MythTvGuide.Program GetProgramDetails(System.Nullable<int> ChanId, System.Nullable<System.DateTime> StartTime) {
            return base.Channel.GetProgramDetails(ChanId, StartTime);
        }
        
        public System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvGuide.Program> GetProgramDetailsAsync(System.Nullable<int> ChanId, System.Nullable<System.DateTime> StartTime) {
            return base.Channel.GetProgramDetailsAsync(ChanId, StartTime);
        }
        
        public babgvant.Emby.MythTv.MythTvGuide.ProgramGuide GetProgramGuide(System.Nullable<System.DateTime> StartTime, System.Nullable<System.DateTime> EndTime, System.Nullable<int> StartChanId, System.Nullable<int> NumChannels, System.Nullable<bool> Details) {
            return base.Channel.GetProgramGuide(StartTime, EndTime, StartChanId, NumChannels, Details);
        }
        
        public System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvGuide.ProgramGuide> GetProgramGuideAsync(System.Nullable<System.DateTime> StartTime, System.Nullable<System.DateTime> EndTime, System.Nullable<int> StartChanId, System.Nullable<int> NumChannels, System.Nullable<bool> Details) {
            return base.Channel.GetProgramGuideAsync(StartTime, EndTime, StartChanId, NumChannels, Details);
        }
    }
}
