//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace babgvant.Emby.MythTv.MythTvVideo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlurayInfo", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class BlurayInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscLangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint DiscNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint TotalDiscNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint TitleCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint ThumbCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TopMenuSupportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FirstPlaySupportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint NumHDMVTitlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint NumBDJTitlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint NumUnsupportedTitlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AACSDetectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LibAACSDetectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AACSHandledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BDPlusDetectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LibBDPlusDetectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BDPlusHandledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AltTitle {
            get {
                return this.AltTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.AltTitleField, value) != true)) {
                    this.AltTitleField = value;
                    this.RaisePropertyChanged("AltTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DiscLang {
            get {
                return this.DiscLangField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscLangField, value) != true)) {
                    this.DiscLangField = value;
                    this.RaisePropertyChanged("DiscLang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public uint DiscNum {
            get {
                return this.DiscNumField;
            }
            set {
                if ((this.DiscNumField.Equals(value) != true)) {
                    this.DiscNumField = value;
                    this.RaisePropertyChanged("DiscNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public uint TotalDiscNum {
            get {
                return this.TotalDiscNumField;
            }
            set {
                if ((this.TotalDiscNumField.Equals(value) != true)) {
                    this.TotalDiscNumField = value;
                    this.RaisePropertyChanged("TotalDiscNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public uint TitleCount {
            get {
                return this.TitleCountField;
            }
            set {
                if ((this.TitleCountField.Equals(value) != true)) {
                    this.TitleCountField = value;
                    this.RaisePropertyChanged("TitleCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public uint ThumbCount {
            get {
                return this.ThumbCountField;
            }
            set {
                if ((this.ThumbCountField.Equals(value) != true)) {
                    this.ThumbCountField = value;
                    this.RaisePropertyChanged("ThumbCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ThumbPath {
            get {
                return this.ThumbPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbPathField, value) != true)) {
                    this.ThumbPathField = value;
                    this.RaisePropertyChanged("ThumbPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool TopMenuSupported {
            get {
                return this.TopMenuSupportedField;
            }
            set {
                if ((this.TopMenuSupportedField.Equals(value) != true)) {
                    this.TopMenuSupportedField = value;
                    this.RaisePropertyChanged("TopMenuSupported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool FirstPlaySupported {
            get {
                return this.FirstPlaySupportedField;
            }
            set {
                if ((this.FirstPlaySupportedField.Equals(value) != true)) {
                    this.FirstPlaySupportedField = value;
                    this.RaisePropertyChanged("FirstPlaySupported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public uint NumHDMVTitles {
            get {
                return this.NumHDMVTitlesField;
            }
            set {
                if ((this.NumHDMVTitlesField.Equals(value) != true)) {
                    this.NumHDMVTitlesField = value;
                    this.RaisePropertyChanged("NumHDMVTitles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public uint NumBDJTitles {
            get {
                return this.NumBDJTitlesField;
            }
            set {
                if ((this.NumBDJTitlesField.Equals(value) != true)) {
                    this.NumBDJTitlesField = value;
                    this.RaisePropertyChanged("NumBDJTitles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public uint NumUnsupportedTitles {
            get {
                return this.NumUnsupportedTitlesField;
            }
            set {
                if ((this.NumUnsupportedTitlesField.Equals(value) != true)) {
                    this.NumUnsupportedTitlesField = value;
                    this.RaisePropertyChanged("NumUnsupportedTitles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool AACSDetected {
            get {
                return this.AACSDetectedField;
            }
            set {
                if ((this.AACSDetectedField.Equals(value) != true)) {
                    this.AACSDetectedField = value;
                    this.RaisePropertyChanged("AACSDetected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public bool LibAACSDetected {
            get {
                return this.LibAACSDetectedField;
            }
            set {
                if ((this.LibAACSDetectedField.Equals(value) != true)) {
                    this.LibAACSDetectedField = value;
                    this.RaisePropertyChanged("LibAACSDetected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public bool AACSHandled {
            get {
                return this.AACSHandledField;
            }
            set {
                if ((this.AACSHandledField.Equals(value) != true)) {
                    this.AACSHandledField = value;
                    this.RaisePropertyChanged("AACSHandled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public bool BDPlusDetected {
            get {
                return this.BDPlusDetectedField;
            }
            set {
                if ((this.BDPlusDetectedField.Equals(value) != true)) {
                    this.BDPlusDetectedField = value;
                    this.RaisePropertyChanged("BDPlusDetected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public bool LibBDPlusDetected {
            get {
                return this.LibBDPlusDetectedField;
            }
            set {
                if ((this.LibBDPlusDetectedField.Equals(value) != true)) {
                    this.LibBDPlusDetectedField = value;
                    this.RaisePropertyChanged("LibBDPlusDetected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public bool BDPlusHandled {
            get {
                return this.BDPlusHandledField;
            }
            set {
                if ((this.BDPlusHandledField.Equals(value) != true)) {
                    this.BDPlusHandledField = value;
                    this.RaisePropertyChanged("BDPlusHandled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VideoMetadataInfo", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class VideoMetadataInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaglineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InetrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CollectionrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AddDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float UserRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EpisodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentalLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WatchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProcessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoverartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FanartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BannerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScreenshotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrailerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvVideo.ArtworkInfoList ArtworkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SubTitle {
            get {
                return this.SubTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTitleField, value) != true)) {
                    this.SubTitleField = value;
                    this.RaisePropertyChanged("SubTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Tagline {
            get {
                return this.TaglineField;
            }
            set {
                if ((object.ReferenceEquals(this.TaglineField, value) != true)) {
                    this.TaglineField = value;
                    this.RaisePropertyChanged("Tagline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Director {
            get {
                return this.DirectorField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorField, value) != true)) {
                    this.DirectorField = value;
                    this.RaisePropertyChanged("Director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Studio {
            get {
                return this.StudioField;
            }
            set {
                if ((object.ReferenceEquals(this.StudioField, value) != true)) {
                    this.StudioField = value;
                    this.RaisePropertyChanged("Studio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Certification {
            get {
                return this.CertificationField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificationField, value) != true)) {
                    this.CertificationField = value;
                    this.RaisePropertyChanged("Certification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Inetref {
            get {
                return this.InetrefField;
            }
            set {
                if ((object.ReferenceEquals(this.InetrefField, value) != true)) {
                    this.InetrefField = value;
                    this.RaisePropertyChanged("Inetref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int Collectionref {
            get {
                return this.CollectionrefField;
            }
            set {
                if ((this.CollectionrefField.Equals(value) != true)) {
                    this.CollectionrefField = value;
                    this.RaisePropertyChanged("Collectionref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string HomePage {
            get {
                return this.HomePageField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePageField, value) != true)) {
                    this.HomePageField = value;
                    this.RaisePropertyChanged("HomePage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<System.DateTime> ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<System.DateTime> AddDate {
            get {
                return this.AddDateField;
            }
            set {
                if ((this.AddDateField.Equals(value) != true)) {
                    this.AddDateField = value;
                    this.RaisePropertyChanged("AddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public float UserRating {
            get {
                return this.UserRatingField;
            }
            set {
                if ((this.UserRatingField.Equals(value) != true)) {
                    this.UserRatingField = value;
                    this.RaisePropertyChanged("UserRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int PlayCount {
            get {
                return this.PlayCountField;
            }
            set {
                if ((this.PlayCountField.Equals(value) != true)) {
                    this.PlayCountField = value;
                    this.RaisePropertyChanged("PlayCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int Season {
            get {
                return this.SeasonField;
            }
            set {
                if ((this.SeasonField.Equals(value) != true)) {
                    this.SeasonField = value;
                    this.RaisePropertyChanged("Season");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public int Episode {
            get {
                return this.EpisodeField;
            }
            set {
                if ((this.EpisodeField.Equals(value) != true)) {
                    this.EpisodeField = value;
                    this.RaisePropertyChanged("Episode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public int ParentalLevel {
            get {
                return this.ParentalLevelField;
            }
            set {
                if ((this.ParentalLevelField.Equals(value) != true)) {
                    this.ParentalLevelField = value;
                    this.RaisePropertyChanged("ParentalLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public bool Visible {
            get {
                return this.VisibleField;
            }
            set {
                if ((this.VisibleField.Equals(value) != true)) {
                    this.VisibleField = value;
                    this.RaisePropertyChanged("Visible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public bool Watched {
            get {
                return this.WatchedField;
            }
            set {
                if ((this.WatchedField.Equals(value) != true)) {
                    this.WatchedField = value;
                    this.RaisePropertyChanged("Watched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public bool Processed {
            get {
                return this.ProcessedField;
            }
            set {
                if ((this.ProcessedField.Equals(value) != true)) {
                    this.ProcessedField = value;
                    this.RaisePropertyChanged("Processed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string HostName {
            get {
                return this.HostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostNameField, value) != true)) {
                    this.HostNameField = value;
                    this.RaisePropertyChanged("HostName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string Coverart {
            get {
                return this.CoverartField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverartField, value) != true)) {
                    this.CoverartField = value;
                    this.RaisePropertyChanged("Coverart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string Fanart {
            get {
                return this.FanartField;
            }
            set {
                if ((object.ReferenceEquals(this.FanartField, value) != true)) {
                    this.FanartField = value;
                    this.RaisePropertyChanged("Fanart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string Banner {
            get {
                return this.BannerField;
            }
            set {
                if ((object.ReferenceEquals(this.BannerField, value) != true)) {
                    this.BannerField = value;
                    this.RaisePropertyChanged("Banner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string Screenshot {
            get {
                return this.ScreenshotField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreenshotField, value) != true)) {
                    this.ScreenshotField = value;
                    this.RaisePropertyChanged("Screenshot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string Trailer {
            get {
                return this.TrailerField;
            }
            set {
                if ((object.ReferenceEquals(this.TrailerField, value) != true)) {
                    this.TrailerField = value;
                    this.RaisePropertyChanged("Trailer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public babgvant.Emby.MythTv.MythTvVideo.ArtworkInfoList Artwork {
            get {
                return this.ArtworkField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtworkField, value) != true)) {
                    this.ArtworkField = value;
                    this.RaisePropertyChanged("Artwork");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtworkInfoList", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class ArtworkInfoList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvVideo.ArtworkInfo[] ArtworkInfosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public babgvant.Emby.MythTv.MythTvVideo.ArtworkInfo[] ArtworkInfos {
            get {
                return this.ArtworkInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtworkInfosField, value) != true)) {
                    this.ArtworkInfosField = value;
                    this.RaisePropertyChanged("ArtworkInfos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtworkInfo", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class ArtworkInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorageGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StorageGroup {
            get {
                return this.StorageGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageGroupField, value) != true)) {
                    this.StorageGroupField = value;
                    this.RaisePropertyChanged("StorageGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VideoMetadataInfoList", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class VideoMetadataInfoList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AsOfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProtoVerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo[] VideoMetadataInfosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int TotalAvailable {
            get {
                return this.TotalAvailableField;
            }
            set {
                if ((this.TotalAvailableField.Equals(value) != true)) {
                    this.TotalAvailableField = value;
                    this.RaisePropertyChanged("TotalAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> AsOf {
            get {
                return this.AsOfField;
            }
            set {
                if ((this.AsOfField.Equals(value) != true)) {
                    this.AsOfField = value;
                    this.RaisePropertyChanged("AsOf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ProtoVer {
            get {
                return this.ProtoVerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProtoVerField, value) != true)) {
                    this.ProtoVerField = value;
                    this.RaisePropertyChanged("ProtoVer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo[] VideoMetadataInfos {
            get {
                return this.VideoMetadataInfosField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoMetadataInfosField, value) != true)) {
                    this.VideoMetadataInfosField = value;
                    this.RaisePropertyChanged("VideoMetadataInfos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VideoLookupList", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class VideoLookupList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AsOfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProtoVerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvVideo.VideoLookup[] VideoLookupsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<System.DateTime> AsOf {
            get {
                return this.AsOfField;
            }
            set {
                if ((this.AsOfField.Equals(value) != true)) {
                    this.AsOfField = value;
                    this.RaisePropertyChanged("AsOf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProtoVer {
            get {
                return this.ProtoVerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProtoVerField, value) != true)) {
                    this.ProtoVerField = value;
                    this.RaisePropertyChanged("ProtoVer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public babgvant.Emby.MythTv.MythTvVideo.VideoLookup[] VideoLookups {
            get {
                return this.VideoLookupsField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoLookupsField, value) != true)) {
                    this.VideoLookupsField = value;
                    this.RaisePropertyChanged("VideoLookups");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VideoLookup", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class VideoLookup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EpisodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaglineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InetrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float UserRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvVideo.ArrayOfString CountriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PopularityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BudgetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RevenueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TMSRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private babgvant.Emby.MythTv.MythTvVideo.ArtworkItem[] ArtworkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SubTitle {
            get {
                return this.SubTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTitleField, value) != true)) {
                    this.SubTitleField = value;
                    this.RaisePropertyChanged("SubTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Season {
            get {
                return this.SeasonField;
            }
            set {
                if ((this.SeasonField.Equals(value) != true)) {
                    this.SeasonField = value;
                    this.RaisePropertyChanged("Season");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Episode {
            get {
                return this.EpisodeField;
            }
            set {
                if ((this.EpisodeField.Equals(value) != true)) {
                    this.EpisodeField = value;
                    this.RaisePropertyChanged("Episode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Tagline {
            get {
                return this.TaglineField;
            }
            set {
                if ((object.ReferenceEquals(this.TaglineField, value) != true)) {
                    this.TaglineField = value;
                    this.RaisePropertyChanged("Tagline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Certification {
            get {
                return this.CertificationField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificationField, value) != true)) {
                    this.CertificationField = value;
                    this.RaisePropertyChanged("Certification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Inetref {
            get {
                return this.InetrefField;
            }
            set {
                if ((object.ReferenceEquals(this.InetrefField, value) != true)) {
                    this.InetrefField = value;
                    this.RaisePropertyChanged("Inetref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Collectionref {
            get {
                return this.CollectionrefField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionrefField, value) != true)) {
                    this.CollectionrefField = value;
                    this.RaisePropertyChanged("Collectionref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string HomePage {
            get {
                return this.HomePageField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePageField, value) != true)) {
                    this.HomePageField = value;
                    this.RaisePropertyChanged("HomePage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<System.DateTime> ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public float UserRating {
            get {
                return this.UserRatingField;
            }
            set {
                if ((this.UserRatingField.Equals(value) != true)) {
                    this.UserRatingField = value;
                    this.RaisePropertyChanged("UserRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public babgvant.Emby.MythTv.MythTvVideo.ArrayOfString Countries {
            get {
                return this.CountriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CountriesField, value) != true)) {
                    this.CountriesField = value;
                    this.RaisePropertyChanged("Countries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int Popularity {
            get {
                return this.PopularityField;
            }
            set {
                if ((this.PopularityField.Equals(value) != true)) {
                    this.PopularityField = value;
                    this.RaisePropertyChanged("Popularity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public int Budget {
            get {
                return this.BudgetField;
            }
            set {
                if ((this.BudgetField.Equals(value) != true)) {
                    this.BudgetField = value;
                    this.RaisePropertyChanged("Budget");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public int Revenue {
            get {
                return this.RevenueField;
            }
            set {
                if ((this.RevenueField.Equals(value) != true)) {
                    this.RevenueField = value;
                    this.RaisePropertyChanged("Revenue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string IMDB {
            get {
                return this.IMDBField;
            }
            set {
                if ((object.ReferenceEquals(this.IMDBField, value) != true)) {
                    this.IMDBField = value;
                    this.RaisePropertyChanged("IMDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string TMSRef {
            get {
                return this.TMSRefField;
            }
            set {
                if ((object.ReferenceEquals(this.TMSRefField, value) != true)) {
                    this.TMSRefField = value;
                    this.RaisePropertyChanged("TMSRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public babgvant.Emby.MythTv.MythTvVideo.ArtworkItem[] Artwork {
            get {
                return this.ArtworkField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtworkField, value) != true)) {
                    this.ArtworkField = value;
                    this.RaisePropertyChanged("Artwork");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://mythtv.org", ItemName="String")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtworkItem", Namespace="http://mythtv.org")]
    [System.SerializableAttribute()]
    public partial class ArtworkItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Thumbnail {
            get {
                return this.ThumbnailField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailField, value) != true)) {
                    this.ThumbnailField = value;
                    this.RaisePropertyChanged("Thumbnail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mythtv.org", ConfigurationName="MythTvVideo.Video")]
    public interface Video {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/AddVideo", ReplyAction="http://mythtv.org/Video/AddVideoResponse")]
        System.Nullable<bool> AddVideo(string FileName, string HostName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/AddVideo", ReplyAction="http://mythtv.org/Video/AddVideoResponse")]
        System.Threading.Tasks.Task<System.Nullable<bool>> AddVideoAsync(string FileName, string HostName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/GetBluray", ReplyAction="http://mythtv.org/Video/GetBlurayResponse")]
        babgvant.Emby.MythTv.MythTvVideo.BlurayInfo GetBluray(string Path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/GetBluray", ReplyAction="http://mythtv.org/Video/GetBlurayResponse")]
        System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.BlurayInfo> GetBlurayAsync(string Path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/GetVideo", ReplyAction="http://mythtv.org/Video/GetVideoResponse")]
        babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo GetVideo(System.Nullable<int> Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/GetVideo", ReplyAction="http://mythtv.org/Video/GetVideoResponse")]
        System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo> GetVideoAsync(System.Nullable<int> Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/GetVideoByFileName", ReplyAction="http://mythtv.org/Video/GetVideoByFileNameResponse")]
        babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo GetVideoByFileName(string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/GetVideoByFileName", ReplyAction="http://mythtv.org/Video/GetVideoByFileNameResponse")]
        System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo> GetVideoByFileNameAsync(string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/GetVideoList", ReplyAction="http://mythtv.org/Video/GetVideoListResponse")]
        babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfoList GetVideoList(System.Nullable<bool> Descending, System.Nullable<int> StartIndex, System.Nullable<int> Count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/GetVideoList", ReplyAction="http://mythtv.org/Video/GetVideoListResponse")]
        System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfoList> GetVideoListAsync(System.Nullable<bool> Descending, System.Nullable<int> StartIndex, System.Nullable<int> Count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/LookupVideo", ReplyAction="http://mythtv.org/Video/LookupVideoResponse")]
        babgvant.Emby.MythTv.MythTvVideo.VideoLookupList LookupVideo(string Title, string Subtitle, string Inetref, System.Nullable<int> Season, System.Nullable<int> Episode, string GrabberType, System.Nullable<bool> AllowGeneric);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/LookupVideo", ReplyAction="http://mythtv.org/Video/LookupVideoResponse")]
        System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.VideoLookupList> LookupVideoAsync(string Title, string Subtitle, string Inetref, System.Nullable<int> Season, System.Nullable<int> Episode, string GrabberType, System.Nullable<bool> AllowGeneric);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/RemoveVideoFromDB", ReplyAction="http://mythtv.org/Video/RemoveVideoFromDBResponse")]
        System.Nullable<bool> RemoveVideoFromDB(System.Nullable<int> Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mythtv.org/Video/RemoveVideoFromDB", ReplyAction="http://mythtv.org/Video/RemoveVideoFromDBResponse")]
        System.Threading.Tasks.Task<System.Nullable<bool>> RemoveVideoFromDBAsync(System.Nullable<int> Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VideoChannel : babgvant.Emby.MythTv.MythTvVideo.Video, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VideoClient : System.ServiceModel.ClientBase<babgvant.Emby.MythTv.MythTvVideo.Video>, babgvant.Emby.MythTv.MythTvVideo.Video {
        
        public VideoClient() {
        }
        
        public VideoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VideoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VideoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VideoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<bool> AddVideo(string FileName, string HostName) {
            return base.Channel.AddVideo(FileName, HostName);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<bool>> AddVideoAsync(string FileName, string HostName) {
            return base.Channel.AddVideoAsync(FileName, HostName);
        }
        
        public babgvant.Emby.MythTv.MythTvVideo.BlurayInfo GetBluray(string Path) {
            return base.Channel.GetBluray(Path);
        }
        
        public System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.BlurayInfo> GetBlurayAsync(string Path) {
            return base.Channel.GetBlurayAsync(Path);
        }
        
        public babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo GetVideo(System.Nullable<int> Id) {
            return base.Channel.GetVideo(Id);
        }
        
        public System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo> GetVideoAsync(System.Nullable<int> Id) {
            return base.Channel.GetVideoAsync(Id);
        }
        
        public babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo GetVideoByFileName(string FileName) {
            return base.Channel.GetVideoByFileName(FileName);
        }
        
        public System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfo> GetVideoByFileNameAsync(string FileName) {
            return base.Channel.GetVideoByFileNameAsync(FileName);
        }
        
        public babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfoList GetVideoList(System.Nullable<bool> Descending, System.Nullable<int> StartIndex, System.Nullable<int> Count) {
            return base.Channel.GetVideoList(Descending, StartIndex, Count);
        }
        
        public System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.VideoMetadataInfoList> GetVideoListAsync(System.Nullable<bool> Descending, System.Nullable<int> StartIndex, System.Nullable<int> Count) {
            return base.Channel.GetVideoListAsync(Descending, StartIndex, Count);
        }
        
        public babgvant.Emby.MythTv.MythTvVideo.VideoLookupList LookupVideo(string Title, string Subtitle, string Inetref, System.Nullable<int> Season, System.Nullable<int> Episode, string GrabberType, System.Nullable<bool> AllowGeneric) {
            return base.Channel.LookupVideo(Title, Subtitle, Inetref, Season, Episode, GrabberType, AllowGeneric);
        }
        
        public System.Threading.Tasks.Task<babgvant.Emby.MythTv.MythTvVideo.VideoLookupList> LookupVideoAsync(string Title, string Subtitle, string Inetref, System.Nullable<int> Season, System.Nullable<int> Episode, string GrabberType, System.Nullable<bool> AllowGeneric) {
            return base.Channel.LookupVideoAsync(Title, Subtitle, Inetref, Season, Episode, GrabberType, AllowGeneric);
        }
        
        public System.Nullable<bool> RemoveVideoFromDB(System.Nullable<int> Id) {
            return base.Channel.RemoveVideoFromDB(Id);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<bool>> RemoveVideoFromDBAsync(System.Nullable<int> Id) {
            return base.Channel.RemoveVideoFromDBAsync(Id);
        }
    }
}
